### ISSUE TITLE
Installation on Mac AND Ubuntu is write protected

### ISSUE THREAD

**Issue by autodidaddict** [ballerina-platform/ballerina-message-broker#489]
**Description:**
Broker doesn't start up on the Mac for a number of reasons, most of which appear to be related to insufficient read/write privileges in the bre directory and sub-directories

**Suggested Labels:**
bug 

**Suggested Assignees:**

**Affected Product Version:**
0.980.1

**OS, DB, other environment details and versions:**    
MacOS High Sierra 10.13.5

**Steps to reproduce:**
Install Ballerina platform from the Mac installer. Set `$JAVA_HOME` accordingly for Mac installation. Type `broker`. You'll see a number of issues:

1) the `logs` directory isn't created, so there's a FileNotFound exception

After I manually created the logs directory and manually set the permissions to global read/write on that directory, I started `broker` again and got the following error trace:

```
ERROR {io.ballerina.messaging.broker.Main} -  Error while starting broker
io.ballerina.messaging.broker.core.BrokerException: Error occurred while storing queue Queue{name='amq.dlq', durable=true, autoDelete=false}
	at io.ballerina.messaging.broker.core.store.dao.impl.QueueDaoImpl.persist(QueueDaoImpl.java:58)
	at io.ballerina.messaging.broker.core.QueueRegistry.addQueue(QueueRegistry.java:67)
	at io.ballerina.messaging.broker.core.BrokerImpl.createQueue(BrokerImpl.java:420)
	at io.ballerina.messaging.broker.core.BrokerImpl.initDefaultDeadLetterQueue(BrokerImpl.java:186)
	at io.ballerina.messaging.broker.core.BrokerImpl.<init>(BrokerImpl.java:126)
	at io.ballerina.messaging.broker.Main.main(Main.java:80)
Caused by: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
INSERT INTO MB_QUEUE_METADATA (QUEUE_NAME, QUEUE_ARGUMENTS) VALUES(?,?) [90097-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Database.checkWritingAllowed(Database.java:1935)
	at org.h2.table.Table.checkWritingAllowed(Table.java:1186)
	at org.h2.engine.User.hasRight(User.java:114)
	at org.h2.engine.User.checkRight(User.java:100)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.ballerina.messaging.broker.core.store.dao.impl.QueueDaoImpl.persist(QueueDaoImpl.java:52)
	... 5 more
Exception in thread "main" io.ballerina.messaging.broker.core.BrokerException: Error occurred while storing queue Queue{name='amq.dlq', durable=true, autoDelete=false}
	at io.ballerina.messaging.broker.core.store.dao.impl.QueueDaoImpl.persist(QueueDaoImpl.java:58)
	at io.ballerina.messaging.broker.core.QueueRegistry.addQueue(QueueRegistry.java:67)
	at io.ballerina.messaging.broker.core.BrokerImpl.createQueue(BrokerImpl.java:420)
	at io.ballerina.messaging.broker.core.BrokerImpl.initDefaultDeadLetterQueue(BrokerImpl.java:186)
	at io.ballerina.messaging.broker.core.BrokerImpl.<init>(BrokerImpl.java:126)
	at io.ballerina.messaging.broker.Main.main(Main.java:80)
Caused by: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
INSERT INTO MB_QUEUE_METADATA (QUEUE_NAME, QUEUE_ARGUMENTS) VALUES(?,?) [90097-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Database.checkWritingAllowed(Database.java:1935)
	at org.h2.table.Table.checkWritingAllowed(Table.java:1186)
	at org.h2.engine.User.hasRight(User.java:114)
	at org.h2.engine.User.checkRight(User.java:100)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.ballerina.messaging.broker.core.store.dao.impl.QueueDaoImpl.persist(QueueDaoImpl.java:52)
	... 5 more
```

**Comment by autodidaddict** [comment]
I just ran `/usr/lib/ballerina/ballerina-0.980.1/bin/broker` on my Ubuntu 18.04 (PopOS!) laptop and it gave me the _exact_ same error message - first the inability to write to the `logs` directory and then the errors about the database being read only.

**Comment by autodidaddict** [comment]
I can get the broker to start with `sudo broker`, but the "By Guide" example for message broker just says to type `broker`. I think either the documentation should mention the sudo requirement, or the installation shouldn't require root privileges to run `broker`

**Comment by Asitha** [comment]
@keizer619 It seems like we are installing with root. Shall we check this and update the installer?

**Comment by Asitha** [comment]
@keizer619 @autodidaddict We have an upcoming feature that is trying to separate out the BROKER_HOME and the broker runtime [1]. Once this is complete we will be able to get the broker runtime created with user permissions. That should solve this issue. Until then we will have to manually change the permissions in database and logs directory.

[1] https://github.com/ballerina-platform/ballerina-message-broker/issues/408

**Comment by pamod** [comment]
Closing the issue. Since this is fixed.
